/home/praba/Projects/RISCV/final/riscv_soc/rtl/soc_pkg.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/riscv_pkg.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/ctrl_ext.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/alu.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/branch_logic.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/control_unit.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/data_mem.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/decode.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/instr_mem.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/pc_register.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/reg_file.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/riscv_core_ext.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/core/riscv_core.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/bus/ahb_dmem_slave.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/bus/ahb_interconnect.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/bus/ahb_master_riscv.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/bus/ahb_to_apb_bridge.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/periph/i2c_apb.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/periph/spi_apb.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/periph/timer_apb.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/periph/uart_apb.sv
/home/praba/Projects/RISCV/final/riscv_soc/rtl/riscv_soc_top.sv
/home/praba/Projects/RISCV/final/riscv_soc/tb/tb_soc_uart.sv
